### ISSUE TITLE
Add additional categories to collection types

### ISSUE THREAD

**Issue by ilmtest** [ilmtest/search-engine#415]
- Aqeedah
- Siyar / Tarajim
- Usul al-Tafsir  
- Mustalah 
- Usul al-Fiqh
- Qawaid al-Fiqhiyyah
- Seeking Knowledge
- Akhlaq
- Manhaj

**Comment by doxala** [comment]
al-Qawaʾid al-Fiqhiyyah*

**Comment by ilmtest** [comment]
01ea460a7708e19ab59810f9498fcc3570ea17d6
